router_settings:
  routing_strategy: simple-shuffle
  enable_pre_call_check: true
  # redis_url: "redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:6379/0"
  num_retries: 2
  allowed_fails: 3
  cooldown_time: 300
  cache_responses: true
  enable_pre_call_checks: true

model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: "os.environ/OPENAI_API_KEY_FREE"
      input_cost_per_token: 0.000000001
      output_cost_per_token: 0.000000001
      weight: 100
  #
  - model_name: gpt-4.1-mini
    litellm_params:
      model: openai/gpt-4.1-mini
      api_key: "os.environ/OPENAI_API_KEY_FREE"
      input_cost_per_token: 0.000000001
      output_cost_per_token: 0.000000001
      weight: 100
  #
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_key: "os.environ/OPENAI_API_KEY_FREE"
      input_cost_per_token: 0.000000001
      output_cost_per_token: 0.000000001
      weight: 100
  #

litellm_settings:
  request_timeout: 300
  telemetry: False
  drop_params: True
  json_logs: False

  cache: True
  cache_params:
    type: redis
    namespace: "litellm.caching.caching"
    

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
