services:
  dbgate:
    image: dbgate/dbgate:alpine
    container_name: dbgate
    restart: unless-stopped
    volumes:
      - ./data:/root/.dbgate
      - ./config:/app/config
      - ../karakeep/data/db.db:/home/dbgate-docker/sqlite/karakeep.sqlite
    environment:
      LOGIN: ${DBGATE_WEB_LOGIN}
      PASSWORD: ${DBGATE_WEB_PASSWORD}
      CONNECTIONS: con1,con2,con3,con4,con5
      
      # OAuth configuration (web version only)
      OAUTH_AUTH: ${DBGATE_OAUTH_AUTH}
      OAUTH_TOKEN: ${DBGATE_OAUTH_TOKEN}
      OAUTH_LOGOUT: ${DBGATE_OAUTH_LOGOUT}
      OAUTH_CLIENT_ID: ${DBGATE_OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${DBGATE_OAUTH_CLIENT_SECRET}
      OAUTH_LOGIN_FIELD: ${DBGATE_OAUTH_LOGIN_FIELD}
      OAUTH_ALLOWED_LOGINS: ${DBGATE_OAUTH_ALLOWED_LOGINS}
      OAUTH_SCOPE: ${DBGATE_OAUTH_SCOPE}
      OAUTH_GROUP_FIELD: ${DBGATE_OAUTH_GROUP_FIELD}
      OAUTH_ALLOWED_GROUPS: ${DBGATE_OAUTH_ALLOWED_GROUPS}

      LABEL_con1: PostgreSQL
      SERVER_con1: ${POSTGRES_HOST}
      USER_con1: ${POSTGRES_USER}
      PASSWORD_con1: ${POSTGRES_PASSWORD}
      PORT_con1: ${POSTGRES_PORT}
      ENGINE_con1: postgres@dbgate-plugin-postgres

      LABEL_con2: MongoDB
      URL_con2: mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}
      ENGINE_con2: mongo@dbgate-plugin-mongo

      LABEL_con3: ClickHouse
      URL_con3: http://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT_HTTP}
      USER_con3: ${CLICKHOUSE_USER}
      PASSWORD_con3: ${CLICKHOUSE_PASSWORD}
      PORT_con3: ${CLICKHOUSE_PORT_HTTP}
      ENGINE_con3: clickhouse@dbgate-plugin-clickhouse

      LABEL_con4: Redis
      SERVER_con4: ${REDIS_HOST}
      PASSWORD_con4: ${REDIS_PASSWORD}
      PORT_con4: ${REDIS_PORT}
      ENGINE_con4: redis@dbgate-plugin-redis

      LABEL_con5: Karakeep
      FILE_con5: /home/dbgate-docker/sqlite/karakeep.sqlite
      ENGINE_con5: sqlite@dbgate-plugin-sqlite
    networks:
      - web
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dbgate.rule=Host(`dbgate.${BASE_DOMAIN}`)"
      - "traefik.http.routers.dbgate.entrypoints=websecure"
      - "traefik.http.services.dbgate.loadbalancer.server.port=3000"
    env_file:
      - .env
networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
