services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # Set this in your .env file
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Set this in your .env file

    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME} # Using variable from root .env file
