services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      # Provider
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=${WEB_NETWORK_NAME}'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls.certresolver=myresolver'
      # Let's Encrypt
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}'
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme3.json"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      
      # HTTP/3
      - '--entrypoints.websecure.http3'
      # # Logs
      # - '--accesslog.filepath=/logs/access.log'
      # - '--accesslog.format=json'
      # - '--log.filepath=/logs/traefik.log'
      # - '--log.format=json'
      - '--log.level=${TRAEFIK_LOG_LEVEL:-DEBUG}'
      # - '--metrics.prometheus.addrouterslabels'
      # Misc
      - '--api.dashboard'
      # - '--entrypoints.websecure.http.middlewares=compress@file,headers@file${TRAEFIK_PLUGINS:-}'
      # - '--experimental.plugins.fail2ban.modulename=github.com/tommoulard/fail2ban'
      # - '--experimental.plugins.fail2ban.version=v0.6.0'
      # - '--global.checknewversion=false'
      - '--global.sendanonymoususage=false'
      # - '--ping'
      # - '--providers.file.directory=/dynamic_conf/'
      # - '--providers.file.watch=true'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./config:/dynamic_conf:ro
      - ./data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
    labels:
      # --- Dashboard Configuration ---
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${DASHBOARD_AUTH}"

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - web
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${BASE_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME} # Using variable from root .env file
