# onestack/traefik/config/traefik.yml

# -- API and Dashboard --
# Enable the API and dashboard. The dashboard is not exposed to the internet here.
# It will be exposed via Docker labels in the docker-compose file.
api:
  dashboard: true

# -- Entrypoints --
# Define the network entry points for Traefik.
entryPoints:
  web:
    address: ":80"
    # Redirect all HTTP traffic to the 'websecure' (HTTPS) entrypoint.
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    # --- ADDED THIS SECTION ---
    # Make 'myresolver' the default certificate resolver for this entrypoint.
    http:
      tls:
        certResolver: myresolver

# -- Providers --
# Enable the Docker provider to detect services automatically.
providers:
  docker:
    exposedByDefault: false # Do not expose all containers by default for security.

# -- Certificate Resolvers --
# Configure the Let's Encrypt resolver for automatic SSL certificates.
certificatesResolvers:
  myresolver:
    acme:
      httpChallenge:
        entryPoint: web
