services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: >-
      --schedule "0 0 5 * * *"
      --notifications-hostname oracle2.madpin.dev
      --cleanup
      --remove-volumes
      --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Dublin # Set timezone for accurate scheduling
    env_file:
      - .env # For Watchtower notification settings, etc.
# By default, Watchtower does not join any user-defined networks.
# It uses Docker's default bridge network for internet access to check images.
# It interacts with other containers via the Docker socket.
