services:
  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meilisearch
    restart: unless-stopped
    env_file: 
      - ../../.env
      - .env
    volumes:
      - ./data:/meili_data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7700/health | grep -q '{\"status\":\"available\"}'"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  internal_network:
    external: true
    name: ${WEB_NETWORK_NAME}
