services:
  meilisearch:
    image: getmeili/meilisearch:v1.15
    container_name: meilisearch
    restart: unless-stopped
    volumes:
      - ./data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
    env_file: 
      - ../../.env # Loads from root .env first
      - .env       # Then service-specific .env for potential overrides
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7700/health | grep -q '{\"status\":\"available\"}'"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
