services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --save 900 1
      --save 300 10
      --save 60 10000
      --dir /data
      --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME} # Using variable from root .env file
