services:
  ttrss:
    image: nventiveux/ttrss:latest
    container_name: ttrss
    restart: unless-stopped
    volumes:
      - ./config:/var/www/html/config.d
      - ./data:/var/www/html
      - ./config/plugins.local:/srv/ttrss/plugins.local
      - ./config/themes.local:/srv/ttrss/themes.local
    environment:
      - TTRSS_SELF_URL_PATH=https://ttrss.${BASE_DOMAIN}
      - TTRSS_HTTP_HOST=0.0.0.0 # Listen on all interfaces in container

      # Database Connection
      - TTRSS_DB_USER=${POSTGRES_USER}
      - TTRSS_DB_PASS=${POSTGRES_PASSWORD}
      - TTRSS_DB_NAME=${POSTGRES_TTRSS_DB}
      - TTRSS_DB_HOST=${POSTGRES_HOST}
      - TTRSS_DB_PORT=${POSTGRES_PORT}

      # User and File Ownership
      - OWNER_UID=${UID}
      - OWNER_GID=${GID}

      # Auto User Creation & Admin
      - ADMIN_USER_ACCESS_LEVEL=-2 # Access level for admin user
      - AUTO_CREATE_USER=${AUTO_CREATE_USER}
      - AUTO_CREATE_USER_PASS=${AUTO_CREATE_USER_PASS}
      # - HTTP_PORT=8280 # Uncomment and set Traefik service port if TTRSS listens on a non-80 port
    networks:
      - internal_network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ttrss.rule=Host(`ttrss.${BASE_DOMAIN}`)"
      - "traefik.http.routers.ttrss.entrypoints=websecure"
      # - "traefik.http.services.ttrss.loadbalancer.server.port=80" # Assuming service listens on port 80 internally by default

  mercury-parser-api:
    image: wangqiru/mercury-parser-api
    container_name: mercury-parser-api
    restart: unless-stopped
    networks:
      - internal_network

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
