services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      - PGID=${GID}
      - PUID=${UID}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`tabs.${BASE_DOMAIN}`)"
      - "traefik.http.routers.organizr.entrypoints=websecure"

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
