services:
  searxng:
    image: searxng/searxng:latest
    container_name: shared-searxng
    restart: unless-stopped
    volumes:
      - ./config:/etc/searxng/ # Mounts the SearXNG settings.yml and other configs
    environment:
      - BASE_URL=https://searxng.${BASE_DOMAIN}/
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
    networks:
      - web
      - tailscale_network # Or internal_network if not using Tailscale for this
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${BASE_DOMAIN}`)"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME} # Ensure this is defined in root .env
  tailscale_network: # Ensure this is defined in root .env if used
    external: true
    name: ${TAILSCALE_NETWORK_NAME}
