services:
  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./data:/data
      - ./config:/conf
      - ./config/init_data.json:/init_data.json
    environment:
      # Running in Docker mode
      RUNNING_IN_DOCKER: 'true'
      
      # Database configuration
      driverName: postgres
      dataSourceName: "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=${POSTGRES_HOST} port=${POSTGRES_PORT} sslmode=disable dbname=postgres"
      
      # App configuration
      httpPort: 8000
      runmode: prod
      

    networks:
      - web
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.casdoor.rule=Host(`casdoor.${BASE_DOMAIN}`)"
      - "traefik.http.routers.casdoor.entrypoints=websecure"
      - "traefik.http.services.casdoor.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/get-global-providers || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
