services:
  chrome:
    image: zenika/alpine-chrome
    restart: unless-stopped
    networks:
      - internal_network
    command:
      - chromium-browser
      - --headless
      - --disable-gpu
      - --no-sandbox
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222

networks:
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
