services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: karakeep
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      NEXTAUTH_URL: https://karakeep.${BASE_DOMAIN}
      BROWSER_WEB_URL: ${CHROME_ADDR}
      OAUTH_WELLKNOWN_URL: ${KARAKEEP_OAUTH_WELLKNOWN_URL}
      OAUTH_CLIENT_ID: ${KARAKEEP_OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${KARAKEEP_OAUTH_CLIENT_SECRET}
      OAUTH_PROVIDER_NAME: ${KARAKEEP_OAUTH_PROVIDER_NAME}
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: true
      SMTP_HOST: ${SMTP_BREVO_HOST}
      SMTP_PORT: ${SMTP_BREVO_PORT}
      SMTP_USER: ${SMTP_BREVO_USER}
      SMTP_PASSWORD: ${SMTP_BREVO_PASS}
      SMTP_SECURE: false
      SMTP_FROM: ${SMTP_BREVO_USER}
    env_file:
      - .env
      - ./.env
    networks:
      - web
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.rule=Host(`karakeep.${BASE_DOMAIN}`)"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
