services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: librechat-api
    restart: unless-stopped
    ports:
      - "3080:3080"
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@mongodb:27017/librechat?authSource=admin
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    env_file:
      - .env
    networks:
      - web
      - internal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`librechat.${BASE_DOMAIN}`)"
      - "traefik.http.routers.librechat.entrypoints=websecure"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"
    depends_on:
      - rag_api

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: librechat-rag-api
    restart: unless-stopped
    environment:
      # - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/librechat
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=librechat
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAG_PORT=${RAG_PORT:-8000}
    env_file:
      - .env
    networks:
      - internal_network

# Use shared services for mongodb, meilisearch, and postgres
  # mongodb, meilisearch, and postgres are provided by shared stacks

networks:
  web:
    external: true
    name: ${WEB_NETWORK_NAME}
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
