services:
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    container_name: clickhouse
    hostname: clickhouse
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DEFAULT_DATABASE=${CLICKHOUSE_DB}
      - CLICKHOUSE_DEFAULT_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_LOG_LEVEL=information
      - CLICKHOUSE_MAX_MEMORY_USAGE=0
      - CLICKHOUSE_MAX_MEMORY_USAGE_FOR_USER=0
    networks:
      - internal_network
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
